import type { Metadata } from 'next';
import localFont from 'next/font/local';

import Layout from '@components/layout/Layout';

import '@styles/globals.css';

const kataGrotesk = localFont({
  src: [
    {
      path: '../../public/fonts/KataGrotesk-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/KataGrotesk-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/KataGrotesk-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/KataGrotesk-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang='en'>
      <body className={kataGrotesk.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
